apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbclaim
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
